
package tech.fatalist.itmo.lab3.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-09T19:04:43.341+03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "ObjectNotFoundException", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/")
public class ObjectNotFoundException extends Exception {

    private tech.fatalist.itmo.lab3.client.WebExceptionDetails faultInfo;

    public ObjectNotFoundException() {
        super();
    }

    public ObjectNotFoundException(String message) {
        super(message);
    }

    public ObjectNotFoundException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ObjectNotFoundException(String message, tech.fatalist.itmo.lab3.client.WebExceptionDetails objectNotFoundException) {
        super(message);
        this.faultInfo = objectNotFoundException;
    }

    public ObjectNotFoundException(String message, tech.fatalist.itmo.lab3.client.WebExceptionDetails objectNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = objectNotFoundException;
    }

    public tech.fatalist.itmo.lab3.client.WebExceptionDetails getFaultInfo() {
        return this.faultInfo;
    }
}
