package tech.fatalist.itmo.lab3.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-09T19:04:43.359+03:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "PersonService",
                  wsdlLocation = "file:/C:/Users/79312/IdeaProjects/itmo-web-services/lab3/src/main/java/tech/fatalist/itmo/lab3/client/PersonService.wsdl",
                  targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/")
public class PersonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://standalone.service.lab3.itmo.fatalist.tech/", "PersonService");
    public final static QName PersonWebServicePort = new QName("http://standalone.service.lab3.itmo.fatalist.tech/", "PersonWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/79312/IdeaProjects/itmo-web-services/lab3/src/main/java/tech/fatalist/itmo/lab3/client/PersonService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/79312/IdeaProjects/itmo-web-services/lab3/src/main/java/tech/fatalist/itmo/lab3/client/PersonService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonWebService
     */
    @WebEndpoint(name = "PersonWebServicePort")
    public PersonWebService getPersonWebServicePort() {
        return super.getPort(PersonWebServicePort, PersonWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonWebService
     */
    @WebEndpoint(name = "PersonWebServicePort")
    public PersonWebService getPersonWebServicePort(WebServiceFeature... features) {
        return super.getPort(PersonWebServicePort, PersonWebService.class, features);
    }

}
