package tech.fatalist.itmo.lab3.client;

import org.apache.cxf.interceptor.OutInterceptors;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-09T19:04:43.352+03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", name = "PersonWebService")
@XmlSeeAlso({ObjectFactory.class})
@OutInterceptors(classes = {AuthFilter.class})
public interface PersonWebService {

    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.DeletePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public tech.fatalist.itmo.lab3.client.DeletionResult deletePerson(

        @WebParam(name = "id", targetNamespace = "")
        int id
    ) throws ObjectNotFoundException, SQLException_Exception;

    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.CreatePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public tech.fatalist.itmo.lab3.client.CreationResult createPerson(

        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "surname", targetNamespace = "")
        java.lang.String surname,
        @WebParam(name = "age", targetNamespace = "")
        java.lang.Integer age,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "avatar", targetNamespace = "")
        byte[] avatar
    ) throws SQLException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.GetPersonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<tech.fatalist.itmo.lab3.client.Person> getPersons(

        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "surname", targetNamespace = "")
        java.lang.String surname,
        @WebParam(name = "age", targetNamespace = "")
        java.lang.Integer age,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city
    ) throws SQLException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://standalone.service.lab3.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab3.client.UpdatePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public tech.fatalist.itmo.lab3.client.UpdateResult updatePerson(

        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "surname", targetNamespace = "")
        java.lang.String surname,
        @WebParam(name = "age", targetNamespace = "")
        java.lang.Integer age,
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "city", targetNamespace = "")
        java.lang.String city,
        @WebParam(name = "avatar", targetNamespace = "")
        byte[] avatar
    ) throws ObjectNotFoundException, SQLException_Exception;
}
