package tech.fatalist.itmo.lab1.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-21T19:32:18.865+03:00
 * Generated source version: 3.4.2
 */
public final class PersonWebService_PersonWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://standalone.service.lab1.itmo.fatalist.tech/", "PersonService");

    private PersonWebService_PersonWebServicePort_Client() {
    }

    public static void main(String[] args) {
        URL wsdlURL = PersonService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonService ss = new PersonService(wsdlURL, SERVICE_NAME);
        PersonWebService port = ss.getPersonWebServicePort();

        {
            System.out.println("Invoking getPersons...");
            java.util.List<tech.fatalist.itmo.lab1.common.Person> _getPersons__return = port.getPersons();
            System.out.println("getPersons.result=" + _getPersons__return);


        }

        System.exit(0);
    }

}
