package tech.fatalist.itmo.lab1.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-21T19:32:18.920+03:00
 * Generated source version: 3.4.2
 */
@WebService(targetNamespace = "http://standalone.service.lab1.itmo.fatalist.tech/", name = "PersonWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonWebService {

    @WebMethod
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://standalone.service.lab1.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab1.client.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://standalone.service.lab1.itmo.fatalist.tech/", className = "tech.fatalist.itmo.lab1.client.GetPersonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.util.List<tech.fatalist.itmo.lab1.common.Person> getPersons()
            ;
}
