
package tech.fatalist.itmo.lab2.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-04-11T23:20:12.751+03:00
 * Generated source version: 3.4.2
 *
 */
public final class PersonWebService_PersonWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://standalone.service.lab2.itmo.fatalist.tech/", "PersonService");

    private PersonWebService_PersonWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonService ss = new PersonService(wsdlURL, SERVICE_NAME);
        PersonWebService port = ss.getPersonWebServicePort();

        {
        System.out.println("Invoking getPersons...");
        java.lang.String _getPersons_name = "";
        java.lang.String _getPersons_surname = "";
        java.lang.Integer _getPersons_age = null;
        java.lang.String _getPersons_country = "";
        java.lang.String _getPersons_city = "";
        try {
            java.util.List<tech.fatalist.itmo.lab2.client.Person> _getPersons__return = port.getPersons(_getPersons_name, _getPersons_surname, _getPersons_age, _getPersons_country, _getPersons_city);
            System.out.println("getPersons.result=" + _getPersons__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking updatePerson...");
        int _updatePerson_id = 0;
        java.lang.String _updatePerson_name = "";
        java.lang.String _updatePerson_surname = "";
        java.lang.Integer _updatePerson_age = null;
        java.lang.String _updatePerson_country = "";
        java.lang.String _updatePerson_city = "";
        byte[] _updatePerson_avatar = new byte[0];
        try {
            tech.fatalist.itmo.lab2.client.UpdateResult _updatePerson__return = port.updatePerson(_updatePerson_id, _updatePerson_name, _updatePerson_surname, _updatePerson_age, _updatePerson_country, _updatePerson_city, _updatePerson_avatar);
            System.out.println("updatePerson.result=" + _updatePerson__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deletePerson...");
        int _deletePerson_id = 0;
        try {
            tech.fatalist.itmo.lab2.client.DeletionResult _deletePerson__return = port.deletePerson(_deletePerson_id);
            System.out.println("deletePerson.result=" + _deletePerson__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking createPerson...");
        java.lang.String _createPerson_name = "";
        java.lang.String _createPerson_surname = "";
        java.lang.Integer _createPerson_age = null;
        java.lang.String _createPerson_country = "";
        java.lang.String _createPerson_city = "";
        byte[] _createPerson_avatar = new byte[0];
        try {
            tech.fatalist.itmo.lab2.client.CreationResult _createPerson__return = port.createPerson(_createPerson_name, _createPerson_surname, _createPerson_age, _createPerson_country, _createPerson_city, _createPerson_avatar);
            System.out.println("createPerson.result=" + _createPerson__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
